Repository inclusive-design/standards.inclusivedesign.ca, pull requests merged in 2025-07, with the labels that each got.

#264 fix: update resources i18n structure in the CMS
  src/admin/config.yml
Labels: bug

#268 fix(deps): upgrade to Biome v2
  biome.jsonc
  package-lock.json
  package.json
  src/_data/contact.json
  src/_data/languages.json
  src/_data/site.json
  src/_data/translations/en.json
  src/_data/translations/fr.json
  src/assets/styles/base/_base.css
  src/assets/styles/base/_fonts.css
  src/assets/styles/collections/_projects.css
  src/assets/styles/collections/_resources.css
  src/assets/styles/components/_checkbox.css
  src/assets/styles/components/_disclosure.css
  src/assets/styles/components/_filters.css
  src/assets/styles/components/_navigation.css
  src/assets/styles/components/_pagination.css
  src/assets/styles/components/_project-panel.css
  src/assets/styles/components/_select.css
  src/assets/styles/components/_tag.css
Labels: dependencies

#269 feat: use singletons for editing contact info and languages
  src/admin/config.yml
Labels: enhancement
