Repository inclusive-design/standards.inclusivedesign.ca, pull requests merged in 2025-01, with the labels that each got.

#50 fix: resolve some localization issues
  .github/workflows/auto-merge.yml
  .github/workflows/lint-and-test.yml
  eleventy.config.js
  package-lock.json
  package.json
  src/_includes/partials/global/header.njk
  src/assets/styles/app.css
  src/assets/styles/base/_utils.css
  src/assets/styles/global/header.css
  src/collections/pages/fr/about.md
  src/collections/pages/fr/projects.md
Labels: bug

#53 chore(i18n): add translations for header
  src/_data/translations.json
Labels: enhancement

#67 feat: add site metadata (resolves #66)
  src/_data/site.json
  src/_includes/layouts/base.njk
  src/_includes/partials/global/meta.njk
  src/admin/admin.njk
  src/admin/config.yml
  src/collections/pages/en/about.md
  src/collections/pages/en/projects.md
  src/collections/pages/fr/about.md
  src/collections/pages/fr/projects.md
  src/collections/projects/en/all-standards-with-us.md
  src/collections/projects/fr/all-standards-with-us.md
Labels: enhancement

#68 fix: style issues (resolves #64)
  src/assets/styles/base/_base.css
Labels: enhancement

#70 feat: add banner image
  src/_includes/layouts/base.njk
  src/_includes/svg/filters.svg
  src/admin/config.yml
  src/assets/styles/base/_base.css
  src/assets/uploads/homeBanner.png
  src/collections/pages/en/index.md
  src/collections/pages/fr/index.md
Labels: enhancement

#72 feat: structural cleanup, link and navigation styles, project page
  eleventy.config.js
  package-lock.json
  package.json
  src/_data/translations.json
  src/_includes/layouts/about.njk
  src/_includes/layouts/base.njk
  src/_includes/layouts/home.njk
  src/_includes/layouts/project.njk
  src/_includes/layouts/projects.njk
  src/_includes/partials/components/navigation.njk
  src/_includes/partials/global/footer.njk
  src/_includes/partials/global/header.njk
  src/_includes/partials/global/stylesheets.njk
  src/_transforms/parse.js
  src/admin/config.yml
  src/assets/styles/abstracts/_variables.css
  src/assets/styles/app.css
  src/assets/styles/base/_base.css
  src/assets/styles/base/_typography.css
  src/assets/styles/base/_utils.css
  src/assets/styles/collections/_announcements.css
  src/assets/styles/collections/_projects.css
  src/assets/styles/collections/_resources.css
  src/assets/styles/components/_card.css
  src/assets/styles/components/_navigation.css
  src/assets/styles/components/_project-panel.css
  src/assets/styles/components/navigation.css
  src/assets/styles/global/_footer.css
  src/assets/styles/global/_header.css
  src/assets/styles/global/footer.css
  src/collections/projects/projects.11tydata.js
Labels: enhancement

#76 fix: resolve nav link sizing issue on desktop
  src/assets/styles/components/_navigation.css
Labels: bug

#79 chore(deps): reconfigure renovate
  renovate.json
Labels: dependencies

#75 fix: set default layout for projects in cms
  src/assets/styles/components/_card.css
  src/assets/styles/components/_project-panel.css
  src/collections/projects/en/all-standards-with-us.md
  src/collections/projects/en/review-of-the-review.md
  src/collections/projects/fr/all-standards-with-us.md
  src/collections/projects/fr/review-of-the-review.md
  src/collections/projects/projects.11tydata.js
Labels: bug

#82 fix: resolve UIO positioning bug (resolves #78)
  src/_includes/partials/global/header.njk
  src/assets/styles/global/_header.css
Labels: bug

#84 feat: complete translations
  src/_data/site.json
  src/_data/translations.json
  src/_includes/layouts/about.njk
  src/_includes/layouts/base.njk
  src/_includes/layouts/home.njk
  src/_includes/layouts/projects.njk
  src/_includes/partials/components/navigation.njk
  src/_includes/partials/global/footer.njk
  src/_includes/partials/global/meta.njk
  src/assets/styles/abstracts/_variables.css
  src/assets/styles/components/_navigation.css
  src/collections/pages/fr/about.md
  src/collections/projects/fr/all-standards-with-us.md
Labels: enhancement

#91 fix: add all project colours to CMS, make required
  src/admin/config.yml
  src/assets/styles/base/_utils.css
  src/assets/styles/components/_card.css
  src/collections/projects/en/review-of-the-review.md
  src/collections/projects/fr/review-of-the-review.md
Labels: bug

#85 ci: add merge and sync workflows, use app token
  .github/workflows/merge-release.yml
  .github/workflows/release-please.yml
  .github/workflows/sync-branches.yml
  src/admin/config.yml
Labels: enhancement

#81 feat: add skip to contents link
  src/_data/translations.json
  src/_includes/layouts/base.njk
  src/_includes/partials/global/header.njk
  src/assets/styles/base/_base.css
  src/assets/styles/components/_navigation.css
Labels: enhancement

#94 fix: menu button style issues (resolves #89)
  src/_includes/partials/components/navigation.njk
  src/_includes/svg/menu-close.svg
  src/_includes/svg/menu.svg
  src/assets/styles/components/_navigation.css
Labels: bug

#93 fix: update CMS configuration and translate content
  src/_data/translations.json
  src/admin/config.yml
  src/collections/pages/en/about.md
  src/collections/pages/en/projects.md
  src/collections/pages/fr/about.md
  src/collections/pages/fr/index.md
  src/collections/pages/fr/projects.md
  src/collections/projects/en/all-standards-with-us.md
  src/collections/projects/fr/all-standards-with-us.md
  src/collections/projects/fr/review-of-the-review.md
Labels: enhancement

#95 feat: configure fallback social image
  src/_includes/layouts/base.njk
  src/_includes/partials/global/meta.njk
  src/admin/config.yml
  src/assets/images/social-en.png
  src/assets/images/social-fr.png
  src/collections/pages/en/index.md
  src/collections/pages/fr/index.md
Labels: enhancement

#98 fix: banner image gap (resolves #97)
  src/assets/styles/base/_base.css
Labels: bug

#100 fix: remove inline padding from banner image and fix a projects page …
  src/assets/styles/base/_base.css
  src/collections/pages/fr/projects.md
Labels: bug

#104 feat: configure Crowdin (resolves #88)
  .github/workflows/crowdin.yml
  crowdin.yml
  src/_data/translations.json
  src/_data/translations/en.json
  src/_data/translations/fr.json
Labels: enhancement

#107 ci: adjust Crowdin workflow
  .github/workflows/crowdin.yml
Labels: enhancement

#114 fix: banner max width issue (resolves #112)
  src/_includes/layouts/base.njk
  src/assets/styles/base/_base.css
Labels: bug

#115 fix: resolve header style issues
  src/_includes/layouts/project.njk
  src/_includes/partials/components/card.macro.njk
  src/_includes/partials/components/projectPanel.macro.njk
  src/_includes/partials/global/footer.njk
  src/assets/styles/base/_typography.css
Labels: bug

#124 fix: full bleed navigation background for project sidebar
  src/assets/styles/collections/_projects.css
Labels: bug

#127 feat: configure CMS for announcements, events and resources
  eleventy.config.js
  src/_includes/layouts/about.njk
  src/_includes/layouts/base.njk
  src/_includes/layouts/home.njk
  src/_includes/layouts/project.njk
  src/_includes/layouts/projects.njk
  src/_includes/partials/global/meta.njk
  src/admin/config.yml
  src/collections/announcements/announcements.11tydata.js
  src/collections/announcements/en/en.json
  src/collections/announcements/fr/fr.json
  src/collections/events/en/en.json
  src/collections/events/events.11tydata.js
  src/collections/events/fr/fr.json
  src/collections/pages/en/about.md
  src/collections/pages/en/index.md
  src/collections/pages/en/projects.md
  src/collections/pages/fr/about.md
  src/collections/pages/fr/index.md
  src/collections/pages/fr/projects.md
  src/collections/projects/en/all-standards-with-us.md
  src/collections/projects/en/review-of-the-review.md
  src/collections/projects/fr/all-standards-with-us.md
  src/collections/projects/fr/review-of-the-review.md
  src/collections/resources/en/en.json
  src/collections/resources/fr/fr.json
  src/collections/resources/resources.11tydata.js
  src/collections/topics/en/en.json
  src/collections/topics/fr/fr.json
  src/collections/topics/topics.11tydata.js
Labels: enhancement

#131 fix: allow content to be saved without a translation
  src/admin/config.yml
Labels: bug

#125 feat: add project slug field
  src/_includes/layouts/base.njk
  src/assets/styles/base/_base.css
  src/assets/styles/collections/_projects.css
  src/assets/uploads/asc.png
  src/assets/uploads/canada.svg
  src/collections/projects/en/all-standards-with-us.md
  src/collections/projects/en/communication-access-within-the-accessible-canada-act.md
  src/collections/projects/en/future-of-work-equitable-digital-systems.md
  src/collections/projects/en/informing-standards-for-acoustics-and-the-built-environment.md
  src/collections/projects/en/regulating-the-digital-domain.md
  src/collections/projects/en/review-of-the-review.md
  src/collections/projects/fr/all-standards-with-us.md
  src/collections/projects/fr/communication-access-within-the-accessible-canada-act.md
  src/collections/projects/fr/future-of-work-equitable-digital-systems.md
  src/collections/projects/fr/informing-standards-for-acoustics-and-the-built-environment.md
  src/collections/projects/fr/regulating-the-digital-domain.md
  src/collections/projects/fr/review-of-the-review.md
Labels: enhancement

#132 fix: link interaction styles (resolves #126)
  src/assets/styles/base/_base.css
  src/assets/styles/collections/_projects.css
Labels: bug

#133 feat: button styles (resolves #56)
  src/_includes/layouts/base.njk
  src/_includes/partials/components/navigation.njk
  src/assets/styles/abstracts/_variables.css
  src/assets/styles/base/_base.css
  src/assets/styles/components/_navigation.css
Labels: enhancement

#134 feat: collapsible sections (resolves #58)
  eleventy.config.js
  src/assets/styles/app.css
  src/assets/styles/components/_accordion.css
Labels: enhancement

#141 feat: use custom element for disclosure component
  eleventy.config.js
  src/assets/scripts/app.js
  src/assets/styles/app.css
  src/assets/styles/base/_base.css
  src/assets/styles/components/_disclosure.css
Labels: enhancement

#142 feat: mobile navigation sidebar menu
  src/_includes/layouts/project.njk
  src/_transforms/parse.js
  src/assets/scripts/app.js
  src/assets/styles/collections/_projects.css
  src/assets/styles/components/_disclosure.css
Labels: enhancement

#145 feat: add badges and tags (resolves #136, resolves #137, resolves #138)
  src/_includes/svg/date.svg
  src/_includes/svg/eventTag.svg
  src/_includes/svg/project.svg
  src/_includes/svg/remove.svg
  src/_includes/svg/type.svg
  src/assets/styles/app.css
  src/assets/styles/components/_badge.css
  src/assets/styles/components/_tag.css
Labels: enhancement

#147 feat: replace macros with includes (resolves #146)
  eleventy.config.js
  src/_data/translations/en.json
  src/_data/translations/fr.json
  src/_includes/layouts/about.njk
  src/_includes/layouts/home.njk
  src/_includes/layouts/projects.njk
  src/_includes/partials/components/card--announcement.njk
  src/_includes/partials/components/card--event.njk
  src/_includes/partials/components/card--project.njk
  src/_includes/partials/components/card--resource.njk
  src/_includes/partials/components/card.macro.njk
  src/_includes/partials/components/project-panel.njk
  src/_includes/partials/components/projectPanel.macro.njk
  src/admin/config.yml
  src/assets/styles/components/_card.css
  src/collections/topics/topics.11tydata.js
Labels: enhancement
